#!/usr/bin/env bash
#this script automates the installation of nginx

#installing nginx
apt-get -y update
apt-get install nginx

#set nginx to listen on port 80
ufw allow 'Nginx HTTP'

#set up nginx default landing page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i "/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 302 https://www.youtube.com/watch?v=qh2-tgu1wu4;\n\t}" /etc/nginx/sites-available/default

service nginx restart
