#!/usr/bin/env bash
#this script automates the installation of nginx

#installing nginx
apt-get -y update
apt-get -y install nginx

#set nginx to listen on port 80
ufw allow 'Nginx HTTP'

#set up nginx default landing page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root   /var/www/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
		}
}" > /etc/nginx/sites-available/default

service nginx restart
