#!/usr/bin/env bash
# Displays "Best School" 10 times and "Hi" at the 9th interation


VAR="Best School"
i=0


while [ $i -lt 10 ]
do

	if [ $i -eq 9 ]
	then

		echo "Hi"
	fi
	echo "$VAR"
	((i++))
done
