#!/usr/bin/env bash
#This script gives information about a file


if test -e school
then

	echo "School file exists"
	if test -s school
	then

		echo "School file is not empty"
	else

		echo "School file is empty"
	fi
	if test -f school
	then

		echo "School i a regular file"
	fi
else

	echo "school file does not exist"
fi
